/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTemplatesRouteImport } from './routes/dashboard.templates'
import { Route as DashboardSubscriptionRouteImport } from './routes/dashboard.subscription'
import { Route as DashboardPromptsRouteImport } from './routes/dashboard.prompts'
import { Route as DashboardGenerateRouteImport } from './routes/dashboard.generate'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubscriptionRoute = DashboardSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPromptsRoute = DashboardPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGenerateRoute = DashboardGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/dashboard/generate': typeof DashboardGenerateRoute
  '/dashboard/prompts': typeof DashboardPromptsRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/dashboard/generate': typeof DashboardGenerateRoute
  '/dashboard/prompts': typeof DashboardPromptsRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/dashboard/generate': typeof DashboardGenerateRoute
  '/dashboard/prompts': typeof DashboardPromptsRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/api/checkout'
    | '/dashboard/generate'
    | '/dashboard/prompts'
    | '/dashboard/subscription'
    | '/dashboard/templates'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/api/checkout'
    | '/dashboard/generate'
    | '/dashboard/prompts'
    | '/dashboard/subscription'
    | '/dashboard/templates'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/api/checkout'
    | '/dashboard/generate'
    | '/dashboard/prompts'
    | '/dashboard/subscription'
    | '/dashboard/templates'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subscription': {
      id: '/dashboard/subscription'
      path: '/subscription'
      fullPath: '/dashboard/subscription'
      preLoaderRoute: typeof DashboardSubscriptionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/prompts': {
      id: '/dashboard/prompts'
      path: '/prompts'
      fullPath: '/dashboard/prompts'
      preLoaderRoute: typeof DashboardPromptsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/generate': {
      id: '/dashboard/generate'
      path: '/generate'
      fullPath: '/dashboard/generate'
      preLoaderRoute: typeof DashboardGenerateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardGenerateRoute: typeof DashboardGenerateRoute
  DashboardPromptsRoute: typeof DashboardPromptsRoute
  DashboardSubscriptionRoute: typeof DashboardSubscriptionRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardGenerateRoute: DashboardGenerateRoute,
  DashboardPromptsRoute: DashboardPromptsRoute,
  DashboardSubscriptionRoute: DashboardSubscriptionRoute,
  DashboardTemplatesRoute: DashboardTemplatesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
